title: Dr. Robert Zane
description: A doctor's portfolio
baseurl: ""
url: "https://perplexingpasta.github.io/Doctor-Portfolio"

# Exclude from processing
exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - .bundle
  - .jekyll-cache
  - .github
  - .gitignore

# Other configuration settings
theme: jekyll-theme-primer
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
